# Use a Go base image
FROM golang:1.23-alpine as builder

# Set the current working directory inside the container
WORKDIR /app

# Copy the Go module files
COPY go.mod go.sum ./

# Download the Go modules
RUN go mod download

# Copy the rest of the code
COPY . .

# Build the Go binary
RUN go build -o backend .

# Use a smaller image to run the application
FROM alpine:latest

# Set the working directory inside the container
WORKDIR /root/

# Copy the binary from the builder stage
COPY --from=builder /app/backend .

# Expose the port your app runs on (8080 for Gin)
EXPOSE 8080

# Run the app
CMD ["./backend"]
